name: Test setup-node caching
on: [workflow_dispatch]
jobs:
  run:
    name: Node test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-18.04, macos-latest, windows-latest]
        version: [ '16.x' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@main
      with:
        node-version: ${{ matrix.version }}
        cache: npm
    - name: Node version
      shell: pwsh
      run: node --version
    - name: Yarn version
      run: yarn --version
    - name: Npm version
      shell: pwsh
      run: npm --version
    - name: Install dependencies
      run: npm ci
