name: Test setup-node caching
on: [workflow_dispatch]
jobs:
  run:
    name: Node test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]
        version: [ '12.x' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update yarn
      run: yarn set version berry
    - name: Yarn version
      run: yarn --version
    - name: Generate simple .yarnrc.yml
      run: |
        echo "nodeLinker: node-modules" >> .yarnrc.yml
    - uses: actions/setup-node@main
      with:
        node-version: ${{ matrix.version }}
        cache: yarn
    - name: Node version
      shell: pwsh
      run: node --version
    - name: Yarn version
      run: yarn --version
    - name: Npm version
      shell: pwsh
      run: npm --version
    - name: Install dependencies
      run: yarn install
