name: Test setup-node caching
on: [workflow_dispatch]
jobs:
  run:
    name: Node test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ macos-11 ]
        version: [ '14.x' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Node version
      shell: pwsh
      run: node --version
    - name: Yarn version
      run: yarn --version
    - name: Npm version
      shell: pwsh
      run: npm --version
    - uses: actions/cache@v2
      name: Yarn cache
      timeout-minutes: 2
      with:
        path: '**/node_modules'
        key: macos11-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          macos11-yarn-
    - run: yarn install
      timeout-minutes: 4
