name: Test setup-node caching
on: [workflow_dispatch]
jobs:
  run:
    name: Node test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        version: [ '12.x' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update yarn
      run: yarn set version berry
    - name: Yarn version
      run: yarn --version
    - name: Generate simple .yarnrc.yml
      run: |
        echo "nodeLinker: node-modules" >> .yarnrc.yml
    - name: Generate yarn file
      shell: pwsh
      run: |
        Remove-Item yarn.lock
        yarn install
    - name: Remove dependencies
      shell: pwsh
      run: Remove-Item node_modules -Force -Recurse
    - name: Clean global cache
      run: yarn cache clean --all
    - uses: akv-platform/setup-node@add-caching-for-node-dependencies
      with:
        node-version: ${{ matrix.version }}
        cache: yarn
    - name: Node version
      shell: pwsh
      run: node --version
    - name: Yarn version
      run: yarn --version
    - name: Npm version
      shell: pwsh
      run: npm --version
    - name: Install dependencies
      run: yarn install
    - name: upload screenshot
      if: ${{ always() }}
      uses: actions/upload-artifact@master
      with:
        name: yarn.lock
        path: yarn.lock
