name: Test setup-node caching
on: [workflow_dispatch]
jobs:
  run:
    name: Node test
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [macos-latest]
        version: [ '12.x' ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Generate package lock file
      run: npm install
    - name: Remove dependencies
      shell: pwsh
      run: Remove-Item node_modules -Force -Recurse
    - name: Clean global cache
      run: npm cache clean --force
    - uses: akv-platform/setup-node@add-caching-for-node-dependencies
      with:
        node-version: ${{ matrix.version }}
    - name: Node version
      shell: pwsh
      run: node --version
    - name: Yarn version
      run: yarn --version
    - name: Npm version
      shell: pwsh
      run: npm --version
    - name: Install dependencies
      run: npm install
    - name: upload screenshot
      if: ${{ always() }}
      uses: actions/upload-artifact@master
      with:
        name: package-lock.json
        path: package-lock.json
